# Generated by Django 5.1.1 on 2024-10-01 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_usuario_data_nascimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bibliografia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('autor', models.CharField(max_length=100)),
                ('ano_publicacao', models.IntegerField()),
                ('editora', models.CharField(blank=True, max_length=100, null=True)),
                ('link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='conteudos',
            name='bibliografia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='conteudos', to='app.bibliografia'),
            preserve_default=False,
        ),
    ]
