# Generated by Django 4.2.7 on 2024-10-01 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_conteudos_autor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atividades',
            old_name='responder',
            new_name='pergunta',
        ),
        migrations.RemoveField(
            model_name='atividades',
            name='chat',
        ),
        migrations.AddField(
            model_name='atividades',
            name='resposta',
            field=models.BooleanField(default=False),
        ),
    ]
