# Generated by Django 4.2.7 on 2024-10-01 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_responder_atividades_pergunta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividades',
            name='resposta',
        ),
        migrations.AddField(
            model_name='atividades',
            name='resposta_correta',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
