# Generated by Django 4.2.7 on 2024-10-01 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_pergunta_quiz_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resposta',
            old_name='quiz',
            new_name='Quiz',
        ),
    ]
