# Generated by Django 4.2.7 on 2024-10-18 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_quiz_resposta_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cargo',
            field=models.CharField(blank=True, choices=[('aluno', 'Aluno'), ('professor', 'Professor')], default='aluno', max_length=50, null=True, verbose_name='Cargo'),
        ),
    ]
